/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimeRouteImport } from './routes/_app.time'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppPerformanceIndexRouteImport } from './routes/_app.performance.index'
import { Route as AppMyProjectsIndexRouteImport } from './routes/_app.my-projects.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'
import { Route as ApiAiAssistantRouteImport } from './routes/api/ai.assistant'
import { Route as AppSettingsSmtpRouteImport } from './routes/_app.settings.smtp'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsModulesRouteImport } from './routes/_app.settings.modules'
import { Route as AppSettingsEmployeesRouteImport } from './routes/_app.settings.employees'
import { Route as AppSettingsAutomationRouteImport } from './routes/_app.settings.automation'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppProjectsDashboardRouteImport } from './routes/_app.projects.dashboard'
import { Route as AppPerformanceReviewsRouteImport } from './routes/_app.performance.reviews'
import { Route as AppPerformanceKudosRouteImport } from './routes/_app.performance.kudos'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminPermissionsDiagnoseRouteImport } from './routes/_app.admin.permissions-diagnose'
import { Route as AppAdminPermissionsCheckRouteImport } from './routes/_app.admin.permissions-check'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app.admin.permissions'
import { Route as AppAdminOverviewRouteImport } from './routes/_app.admin.overview'
import { Route as AppAdminHierarchyRouteImport } from './routes/_app.admin.hierarchy'
import { Route as AppAdminEmailProviderRouteImport } from './routes/_app.admin.email-provider'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as ApiPublicHooksSmtpTestRouteImport } from './routes/api/public/hooks/smtp-test'
import { Route as ApiPublicHooksContractAlertsRouteImport } from './routes/api/public/hooks/contract-alerts'
import { Route as ApiPublicHooksAutomationTickRouteImport } from './routes/api/public/hooks/automation-tick'
import { Route as AppProjectsProjectIdDashboardRouteImport } from './routes/_app.projects.$projectId.dashboard'
import { Route as AppMyProjectsProjectIdClientsRouteImport } from './routes/_app.my-projects.$projectId.clients'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceIndexRoute = AppPerformanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPerformanceRoute,
} as any)
const AppMyProjectsIndexRoute = AppMyProjectsIndexRouteImport.update({
  id: '/my-projects/',
  path: '/my-projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai/assistant',
  path: '/api/ai/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsSmtpRoute = AppSettingsSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsModulesRoute = AppSettingsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsEmployeesRoute = AppSettingsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAutomationRoute = AppSettingsAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsDashboardRoute = AppProjectsDashboardRouteImport.update({
  id: '/projects/dashboard',
  path: '/projects/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceReviewsRoute = AppPerformanceReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppPerformanceRoute,
} as any)
const AppPerformanceKudosRoute = AppPerformanceKudosRouteImport.update({
  id: '/kudos',
  path: '/kudos',
  getParentRoute: () => AppPerformanceRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissionsDiagnoseRoute =
  AppAdminPermissionsDiagnoseRouteImport.update({
    id: '/admin/permissions-diagnose',
    path: '/admin/permissions-diagnose',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminPermissionsCheckRoute =
  AppAdminPermissionsCheckRouteImport.update({
    id: '/admin/permissions-check',
    path: '/admin/permissions-check',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOverviewRoute = AppAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHierarchyRoute = AppAdminHierarchyRouteImport.update({
  id: '/admin/hierarchy',
  path: '/admin/hierarchy',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailProviderRoute = AppAdminEmailProviderRouteImport.update({
  id: '/admin/email-provider',
  path: '/admin/email-provider',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksSmtpTestRoute = ApiPublicHooksSmtpTestRouteImport.update({
  id: '/api/public/hooks/smtp-test',
  path: '/api/public/hooks/smtp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksContractAlertsRoute =
  ApiPublicHooksContractAlertsRouteImport.update({
    id: '/api/public/hooks/contract-alerts',
    path: '/api/public/hooks/contract-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationTickRoute =
  ApiPublicHooksAutomationTickRouteImport.update({
    id: '/api/public/hooks/automation-tick',
    path: '/api/public/hooks/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdDashboardRoute =
  AppProjectsProjectIdDashboardRouteImport.update({
    id: '/projects/$projectId/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppMyProjectsProjectIdClientsRoute =
  AppMyProjectsProjectIdClientsRouteImport.update({
    id: '/my-projects/$projectId/clients',
    path: '/my-projects/$projectId/clients',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/performance': typeof AppPerformanceRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/team': typeof AppTeamRoute
  '/time': typeof AppTimeRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/email-provider': typeof AppAdminEmailProviderRoute
  '/admin/hierarchy': typeof AppAdminHierarchyRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/permissions-check': typeof AppAdminPermissionsCheckRoute
  '/admin/permissions-diagnose': typeof AppAdminPermissionsDiagnoseRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/performance/kudos': typeof AppPerformanceKudosRoute
  '/performance/reviews': typeof AppPerformanceReviewsRoute
  '/projects/dashboard': typeof AppProjectsDashboardRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/automation': typeof AppSettingsAutomationRoute
  '/settings/employees': typeof AppSettingsEmployeesRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/smtp': typeof AppSettingsSmtpRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/admin/': typeof AppAdminIndexRoute
  '/my-projects/': typeof AppMyProjectsIndexRoute
  '/performance/': typeof AppPerformanceIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/my-projects/$projectId/clients': typeof AppMyProjectsProjectIdClientsRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/contract-alerts': typeof ApiPublicHooksContractAlertsRoute
  '/api/public/hooks/smtp-test': typeof ApiPublicHooksSmtpTestRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/team': typeof AppTeamRoute
  '/time': typeof AppTimeRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/email-provider': typeof AppAdminEmailProviderRoute
  '/admin/hierarchy': typeof AppAdminHierarchyRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/permissions-check': typeof AppAdminPermissionsCheckRoute
  '/admin/permissions-diagnose': typeof AppAdminPermissionsDiagnoseRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/performance/kudos': typeof AppPerformanceKudosRoute
  '/performance/reviews': typeof AppPerformanceReviewsRoute
  '/projects/dashboard': typeof AppProjectsDashboardRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/automation': typeof AppSettingsAutomationRoute
  '/settings/employees': typeof AppSettingsEmployeesRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/smtp': typeof AppSettingsSmtpRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/admin': typeof AppAdminIndexRoute
  '/my-projects': typeof AppMyProjectsIndexRoute
  '/performance': typeof AppPerformanceIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/my-projects/$projectId/clients': typeof AppMyProjectsProjectIdClientsRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/contract-alerts': typeof ApiPublicHooksContractAlertsRoute
  '/api/public/hooks/smtp-test': typeof ApiPublicHooksSmtpTestRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/performance': typeof AppPerformanceRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/team': typeof AppTeamRoute
  '/_app/time': typeof AppTimeRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/email-provider': typeof AppAdminEmailProviderRoute
  '/_app/admin/hierarchy': typeof AppAdminHierarchyRoute
  '/_app/admin/overview': typeof AppAdminOverviewRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/permissions-check': typeof AppAdminPermissionsCheckRoute
  '/_app/admin/permissions-diagnose': typeof AppAdminPermissionsDiagnoseRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/performance/kudos': typeof AppPerformanceKudosRoute
  '/_app/performance/reviews': typeof AppPerformanceReviewsRoute
  '/_app/projects/dashboard': typeof AppProjectsDashboardRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/automation': typeof AppSettingsAutomationRoute
  '/_app/settings/employees': typeof AppSettingsEmployeesRoute
  '/_app/settings/modules': typeof AppSettingsModulesRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/smtp': typeof AppSettingsSmtpRoute
  '/api/ai/assistant': typeof ApiAiAssistantRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/my-projects/': typeof AppMyProjectsIndexRoute
  '/_app/performance/': typeof AppPerformanceIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/my-projects/$projectId/clients': typeof AppMyProjectsProjectIdClientsRoute
  '/_app/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/contract-alerts': typeof ApiPublicHooksContractAlertsRoute
  '/api/public/hooks/smtp-test': typeof ApiPublicHooksSmtpTestRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/dashboard'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/team'
    | '/time'
    | '/admin/audit'
    | '/admin/email-provider'
    | '/admin/hierarchy'
    | '/admin/overview'
    | '/admin/permissions'
    | '/admin/permissions-check'
    | '/admin/permissions-diagnose'
    | '/admin/roles'
    | '/performance/kudos'
    | '/performance/reviews'
    | '/projects/dashboard'
    | '/settings/audit'
    | '/settings/automation'
    | '/settings/employees'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/smtp'
    | '/api/ai/assistant'
    | '/api/public/seed-admin'
    | '/admin/'
    | '/my-projects/'
    | '/performance/'
    | '/projects/'
    | '/settings/'
    | '/my-projects/$projectId/clients'
    | '/projects/$projectId/dashboard'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/contract-alerts'
    | '/api/public/hooks/smtp-test'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/team'
    | '/time'
    | '/admin/audit'
    | '/admin/email-provider'
    | '/admin/hierarchy'
    | '/admin/overview'
    | '/admin/permissions'
    | '/admin/permissions-check'
    | '/admin/permissions-diagnose'
    | '/admin/roles'
    | '/performance/kudos'
    | '/performance/reviews'
    | '/projects/dashboard'
    | '/settings/audit'
    | '/settings/automation'
    | '/settings/employees'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/smtp'
    | '/api/ai/assistant'
    | '/api/public/seed-admin'
    | '/admin'
    | '/my-projects'
    | '/performance'
    | '/projects'
    | '/settings'
    | '/my-projects/$projectId/clients'
    | '/projects/$projectId/dashboard'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/contract-alerts'
    | '/api/public/hooks/smtp-test'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/performance'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/time'
    | '/_app/admin/audit'
    | '/_app/admin/email-provider'
    | '/_app/admin/hierarchy'
    | '/_app/admin/overview'
    | '/_app/admin/permissions'
    | '/_app/admin/permissions-check'
    | '/_app/admin/permissions-diagnose'
    | '/_app/admin/roles'
    | '/_app/performance/kudos'
    | '/_app/performance/reviews'
    | '/_app/projects/dashboard'
    | '/_app/settings/audit'
    | '/_app/settings/automation'
    | '/_app/settings/employees'
    | '/_app/settings/modules'
    | '/_app/settings/notifications'
    | '/_app/settings/smtp'
    | '/api/ai/assistant'
    | '/api/public/seed-admin'
    | '/_app/admin/'
    | '/_app/my-projects/'
    | '/_app/performance/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/my-projects/$projectId/clients'
    | '/_app/projects/$projectId/dashboard'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/contract-alerts'
    | '/api/public/hooks/smtp-test'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
  ApiPublicHooksAutomationTickRoute: typeof ApiPublicHooksAutomationTickRoute
  ApiPublicHooksContractAlertsRoute: typeof ApiPublicHooksContractAlertsRoute
  ApiPublicHooksSmtpTestRoute: typeof ApiPublicHooksSmtpTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/time': {
      id: '/_app/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/': {
      id: '/_app/performance/'
      path: '/'
      fullPath: '/performance/'
      preLoaderRoute: typeof AppPerformanceIndexRouteImport
      parentRoute: typeof AppPerformanceRoute
    }
    '/_app/my-projects/': {
      id: '/_app/my-projects/'
      path: '/my-projects'
      fullPath: '/my-projects/'
      preLoaderRoute: typeof AppMyProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assistant': {
      id: '/api/ai/assistant'
      path: '/api/ai/assistant'
      fullPath: '/api/ai/assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/smtp': {
      id: '/_app/settings/smtp'
      path: '/smtp'
      fullPath: '/settings/smtp'
      preLoaderRoute: typeof AppSettingsSmtpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/modules': {
      id: '/_app/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AppSettingsModulesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/employees': {
      id: '/_app/settings/employees'
      path: '/employees'
      fullPath: '/settings/employees'
      preLoaderRoute: typeof AppSettingsEmployeesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/automation': {
      id: '/_app/settings/automation'
      path: '/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof AppSettingsAutomationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/dashboard': {
      id: '/_app/projects/dashboard'
      path: '/projects/dashboard'
      fullPath: '/projects/dashboard'
      preLoaderRoute: typeof AppProjectsDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance/reviews': {
      id: '/_app/performance/reviews'
      path: '/reviews'
      fullPath: '/performance/reviews'
      preLoaderRoute: typeof AppPerformanceReviewsRouteImport
      parentRoute: typeof AppPerformanceRoute
    }
    '/_app/performance/kudos': {
      id: '/_app/performance/kudos'
      path: '/kudos'
      fullPath: '/performance/kudos'
      preLoaderRoute: typeof AppPerformanceKudosRouteImport
      parentRoute: typeof AppPerformanceRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions-diagnose': {
      id: '/_app/admin/permissions-diagnose'
      path: '/admin/permissions-diagnose'
      fullPath: '/admin/permissions-diagnose'
      preLoaderRoute: typeof AppAdminPermissionsDiagnoseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions-check': {
      id: '/_app/admin/permissions-check'
      path: '/admin/permissions-check'
      fullPath: '/admin/permissions-check'
      preLoaderRoute: typeof AppAdminPermissionsCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/overview': {
      id: '/_app/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AppAdminOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/hierarchy': {
      id: '/_app/admin/hierarchy'
      path: '/admin/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AppAdminHierarchyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/email-provider': {
      id: '/_app/admin/email-provider'
      path: '/admin/email-provider'
      fullPath: '/admin/email-provider'
      preLoaderRoute: typeof AppAdminEmailProviderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/smtp-test': {
      id: '/api/public/hooks/smtp-test'
      path: '/api/public/hooks/smtp-test'
      fullPath: '/api/public/hooks/smtp-test'
      preLoaderRoute: typeof ApiPublicHooksSmtpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/contract-alerts': {
      id: '/api/public/hooks/contract-alerts'
      path: '/api/public/hooks/contract-alerts'
      fullPath: '/api/public/hooks/contract-alerts'
      preLoaderRoute: typeof ApiPublicHooksContractAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-tick': {
      id: '/api/public/hooks/automation-tick'
      path: '/api/public/hooks/automation-tick'
      fullPath: '/api/public/hooks/automation-tick'
      preLoaderRoute: typeof ApiPublicHooksAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/dashboard': {
      id: '/_app/projects/$projectId/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppProjectsProjectIdDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-projects/$projectId/clients': {
      id: '/_app/my-projects/$projectId/clients'
      path: '/my-projects/$projectId/clients'
      fullPath: '/my-projects/$projectId/clients'
      preLoaderRoute: typeof AppMyProjectsProjectIdClientsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPerformanceRouteChildren {
  AppPerformanceKudosRoute: typeof AppPerformanceKudosRoute
  AppPerformanceReviewsRoute: typeof AppPerformanceReviewsRoute
  AppPerformanceIndexRoute: typeof AppPerformanceIndexRoute
}

const AppPerformanceRouteChildren: AppPerformanceRouteChildren = {
  AppPerformanceKudosRoute: AppPerformanceKudosRoute,
  AppPerformanceReviewsRoute: AppPerformanceReviewsRoute,
  AppPerformanceIndexRoute: AppPerformanceIndexRoute,
}

const AppPerformanceRouteWithChildren = AppPerformanceRoute._addFileChildren(
  AppPerformanceRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsAutomationRoute: typeof AppSettingsAutomationRoute
  AppSettingsEmployeesRoute: typeof AppSettingsEmployeesRoute
  AppSettingsModulesRoute: typeof AppSettingsModulesRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSmtpRoute: typeof AppSettingsSmtpRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsAutomationRoute: AppSettingsAutomationRoute,
  AppSettingsEmployeesRoute: AppSettingsEmployeesRoute,
  AppSettingsModulesRoute: AppSettingsModulesRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSmtpRoute: AppSettingsSmtpRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerformanceRoute: typeof AppPerformanceRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTeamRoute: typeof AppTeamRoute
  AppTimeRoute: typeof AppTimeRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminEmailProviderRoute: typeof AppAdminEmailProviderRoute
  AppAdminHierarchyRoute: typeof AppAdminHierarchyRoute
  AppAdminOverviewRoute: typeof AppAdminOverviewRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminPermissionsCheckRoute: typeof AppAdminPermissionsCheckRoute
  AppAdminPermissionsDiagnoseRoute: typeof AppAdminPermissionsDiagnoseRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppProjectsDashboardRoute: typeof AppProjectsDashboardRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppMyProjectsIndexRoute: typeof AppMyProjectsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppMyProjectsProjectIdClientsRoute: typeof AppMyProjectsProjectIdClientsRoute
  AppProjectsProjectIdDashboardRoute: typeof AppProjectsProjectIdDashboardRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPerformanceRoute: AppPerformanceRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTeamRoute: AppTeamRoute,
  AppTimeRoute: AppTimeRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminEmailProviderRoute: AppAdminEmailProviderRoute,
  AppAdminHierarchyRoute: AppAdminHierarchyRoute,
  AppAdminOverviewRoute: AppAdminOverviewRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminPermissionsCheckRoute: AppAdminPermissionsCheckRoute,
  AppAdminPermissionsDiagnoseRoute: AppAdminPermissionsDiagnoseRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppProjectsDashboardRoute: AppProjectsDashboardRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppMyProjectsIndexRoute: AppMyProjectsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppMyProjectsProjectIdClientsRoute: AppMyProjectsProjectIdClientsRoute,
  AppProjectsProjectIdDashboardRoute: AppProjectsProjectIdDashboardRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
  ApiPublicHooksAutomationTickRoute: ApiPublicHooksAutomationTickRoute,
  ApiPublicHooksContractAlertsRoute: ApiPublicHooksContractAlertsRoute,
  ApiPublicHooksSmtpTestRoute: ApiPublicHooksSmtpTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
